import { z } from 'zod';
export declare const DONEMLER: readonly ["guz", "bahar"];
export declare const DONEMLER_LIST: typeof DONEMLER;
export declare const DonemEnum: z.ZodEnum<["guz", "bahar"]>;
export declare const EXAM_DURUMLARI: readonly ["planlanmadi", "taslak", "yayinlandi"];
export declare const EXAM_DURUM_LISTESI: typeof EXAM_DURUMLARI;
export declare const ExamDurumEnum: z.ZodEnum<["planlanmadi", "taslak", "yayinlandi"]>;
export declare const EXAM_TURLERI: readonly ["sinav", "odev", "proje"];
export declare const EXAM_TUR_LISTESI: typeof EXAM_TURLERI;
export declare const ExamTurEnum: z.ZodEnum<["sinav", "odev", "proje"]>;
export declare const KULLANICI_ROLLERI: readonly ["YONETICI", "BOLUM_SORUMLUSU", "OGRETIM_UYESI"];
export declare const KULLANICI_ROL_LISTESI: typeof KULLANICI_ROLLERI;
export declare const KullaniciRolEnum: z.ZodEnum<["YONETICI", "BOLUM_SORUMLUSU", "OGRETIM_UYESI"]>;
export declare const GUNLER: readonly ["Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma", "Cumartesi", "Pazar"];
export declare const GUN_LISTESI: typeof GUNLER;
export declare const GunEnum: z.ZodEnum<["Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma", "Cumartesi", "Pazar"]>;
export declare const DERSLIK_TIPLERI: readonly ["amfi", "laboratuvar", "sinif", "toplanti", "diger"];
export declare const DERSLIK_TIP_LISTESI: typeof DERSLIK_TIPLERI;
export declare const DerslikTipEnum: z.ZodEnum<["amfi", "laboratuvar", "sinif", "toplanti", "diger"]>;
export type Donem = z.infer<typeof DonemEnum>;
export type ExamDurum = z.infer<typeof ExamDurumEnum>;
export type ExamTur = z.infer<typeof ExamTurEnum>;
export type KullaniciRol = z.infer<typeof KullaniciRolEnum>;
export type Gun = z.infer<typeof GunEnum>;
export type DerslikTip = z.infer<typeof DerslikTipEnum>;
